FROM alpine:3.17.2
RUN apk add --no-cache wget
RUN wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz \
  && tar -xzvf grpcurl_1.8.7_linux_x86_64.tar.gz -C /usr/bin/
# Make container to run forever once started
CMD [ "tail", "-f", "/dev/null"  ]
